---
kind: pipeline
type: docker
name: Default

steps:
- name: Build
  image: golang:alpine
  commands:
  - go install .
  - cp $GOPATH/bin/bchttpd .

- name: Publish
  image: plugins/docker
  settings:
    username:
        from_secret: DOCKER_USERNAME
    password:
        from_secret: DOCKER_PASSWORD
    repo: bradleychatha/bchttpd
    tags: latest

trigger:
  branch:
    - master